{
 "title": "ShopFlow SAGA Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Created (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri='/api/orders',method='POST',job='order-service'}[1h]))",
     "legendFormat": "Orders"
    }
   ]
  },
  {
   "title": "Payments Succeeded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri='/api/payments',method='POST',status='200',job='payment-service'}[1h]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Payments Failed (Compensation)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri='/api/payments',method='POST',status!='200',job='payment-service'}[1h]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Gateway Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{job='api-gateway'}", "legendFormat": "Gateway" }
   ]
  },
  {
   "title": "HTTP Request Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job='order-service'}[1m])",
     "legendFormat": "order-service {{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job='payment-service'}[1m])",
     "legendFormat": "payment-service {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Latency P99 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{job='order-service'}[2m])) * 1000",
     "legendFormat": "order-service p99"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{job='payment-service'}[2m])) * 1000",
     "legendFormat": "payment-service p99"
    }
   ]
  },
  {
   "title": "Live Logs — All Services",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{app=~\"service-order|service-payment\"}"
    }
   ]
  }
 ]
}